// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZaQiqMVnz4SqXFKryiiZ3TYhxVsr6lQ',
    appId: '1:120357826866:web:9b03447fdd29bcc49ba72b',
    messagingSenderId: '120357826866',
    projectId: 'max-food-delivery-app',
    authDomain: 'max-food-delivery-app.firebaseapp.com',
    storageBucket: 'max-food-delivery-app.appspot.com',
    measurementId: 'G-QEBSX6PKXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF1YMcjI9k3j4-Pe-1OFzGE_1LI1RqEo4',
    appId: '1:120357826866:android:706e5e15e0d4de529ba72b',
    messagingSenderId: '120357826866',
    projectId: 'max-food-delivery-app',
    storageBucket: 'max-food-delivery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKZJ-hj-qkxpyC25hqDgXhJ57ME9QKLI',
    appId: '1:120357826866:ios:f55e34d7c169f2979ba72b',
    messagingSenderId: '120357826866',
    projectId: 'max-food-delivery-app',
    storageBucket: 'max-food-delivery-app.appspot.com',
    iosClientId: '120357826866-2uits863me9tepsnfm2sm7eaui8a1c7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.maxFoodDeliveryAdminPanel',
  );
}
